%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/Foster/OneDrive/ME4/FYP/Track Generation/FSUK Track Centreline.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/11/09 01:38:32

%% Initialize variables.
filename = '/Users/Foster/OneDrive/ME4/FYP/Track Generation/FSUK Track Centreline.csv';
delimiter = ',';

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN,  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
FSUKTrackCentreline = table(dataArray{1:end-1}, 'VariableNames', {'VarName1','VarName2'});

%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;

%% Separate into x and y
FSUKTrackCentreline = table2array(FSUKTrackCentreline);
x = FSUKTrackCentreline(: , 1);
y = FSUKTrackCentreline(: , 2);

scatter(x,y,'+');