function Results = Run_Dynamic_Sim(Simulation,Car,Track,Environment,Options,SimSettings)

%% Model Variant Set-up
Vibrations_Model_8DOF = Simulink.Variant('Vibrations_Model == 1');
Vibrations_Model_7DOF = Simulink.Variant('Vibrations_Model == 2');
Vibrations_Model = 1;

%% Initial Conditions

%% Run Simulink Simulation
Results = sim(Simulation,...
    'AbsTol',SimSettings.AbsTol,...
    'AlgebraicLoopMsg',SimSettings.AlgebraicLoopMsg,...
    'ArrayBoundsChecking',SimSettings.ArrayBoundsChecking,...
    'ArtificialAlgebraicLoopMsg',SimSettings.ArtificialAlgebraicLoopMsg,...
    'CheckMatrixSingularityMsg',SimSettings.CheckMatrixSingularityMsg,...
    'CheckModelReferenceTargetMessage',SimSettings.CheckModelReferenceTargetMessage,...
    'CheckSSInitialOutputMsg',SimSettings.CheckSSInitialOutputMsg,...
    'EnableAccessToBaseWorkspace',SimSettings.EnableAccessToBaseWorkspace,...
    'InitialStep',SimSettings.InitialStep,...
    'FixedStep',SimSettings.FixedStep,...
    'InspectSignalLogs',SimSettings.InspectSignalLogs,...
    'LoggingToFile',SimSettings.LoggingToFile,...
    'LoggingFileName',SimSettings.LoggingFileName,...
    'MaxStep',SimSettings.MaxStep,...
    'MinStep',SimSettings.MinStep,...
    'MaxNumMinSteps',SimSettings.MaxNumMinSteps,...
    'OutputSaveName',SimSettings.OutputSaveName,...
    'ParameterDowncastMsg',SimSettings.ParameterDowncastMsg,...
    'ParameterOverflowMsg',SimSettings.ParameterOverflowMsg,...
    'ParameterPrecisionLossMsg',SimSettings.ParameterPrecisionLossMsg,...
    'ParameterTunabilityLossMsg',SimSettings.ParameterTunabilityLossMsg,...
    'ParameterUnderflowMsg',SimSettings.ParameterUnderflowMsg,...
    'RelTol',SimSettings.RelTol,...
    'SaveOutput',SimSettings.SaveOutput,...
    'SaveFormat',SimSettings.SaveFormat,...
    'SaveTime',SimSettings.SaveTime,...
    'SaveWithDisabledLinksMsg',SimSettings.SaveWithDisabledLinksMsg,...
    'SaveWithParameterizedLinksMsg',SimSettings.SaveWithParameterizedLinksMsg,...
    'SignalLogging',SimSettings.SignalLogging,...
    'SignalLoggingName',SimSettings.SignalLoggingName,...
    'SimCtrlC',SimSettings.SimCtrlC,...
    'SimulationMode',SimSettings.SimulationMode,...
    'Solver',SimSettings.Solver,...
    'SolverType',SimSettings.SolverType,...
    'StartTime',SimSettings.StartTime,...
    'StateNameClashWarn',SimSettings.StateNameClashWarn,...
    'StopTime',SimSettings.StopTime,...
    'UnconnectedInputMsg',SimSettings.UnconnectedInputMsg,...
    'UnconnectedLineMsg',SimSettings.UnconnectedLineMsg,...
    'UnconnectedOutputMsg',SimSettings.UnconnectedOutputMsg,...
    'UnderSpecifiedDataTypeMsg',SimSettings.UnderSpecifiedDataTypeMsg,...
    'ZeroCrossAlgorithm',SimSettings.ZeroCrossAlgorithm,...
    'SrcWorkspace',SimSettings.SrcWorkspace,...
    'CaptureErrors',SimSettings.CaptureErrors);
